version: "3.8"

services:
  app:
    container_name: ericdowell
    image: jekyll/builder:4
    command: jekyll serve --incremental
    restart: always
    ports:
      - "4000:4000"
    volumes:
      - ./:/srv/jekyll
