version: 2
jobs:
  test:
    docker:
      - image: circleci/ruby:2.5
    steps:
      - checkout
      - run:
          name: Setup bundle config
          command: mkdir -p .bundle && cp .circleci/bundle-config .bundle/config
      - restore_cache:
          keys:
            - my-jekyll-build-bundle-{{ checksum "Gemfile.lock" }}-vendor-bundle
      - run:
          name: Bundle Install
          command: ./script/bootstrap
      - save_cache:
          key: my-jekyll-build-bundle-{{ checksum "Gemfile.lock" }}-vendor-bundle
          paths:
            - vendor/bundle
      - run:
          name: Build Site
          command: ./script/build
      - run: Test that the site was built correctly
        command: |
          if test -e "./_site/index.html";then
            echo "It builds!"
          else
            echo "Huh. That's odd. The example site doesn't seem to build."
            exit 1
          fi
workflows:
  version: 2
  test_jekyll_build:
    jobs:
      - test
