version: 2
jobs:
  test:
    docker:
      - image: circleci/ruby:2.5
    environment:
      TZ: "/usr/share/zoneinfo/America/Chicago"
    steps:
      - checkout

      - restore_cache:
          keys:
            - my-jekyll-build-bundle-{{ checksum "Gemfile.lock" }}-usr-local-bundle

      - run:
          name: Bundle Install
          command: ./script/bootstrap

      - save_cache:
          key: my-jekyll-build-bundle-{{ checksum "Gemfile.lock" }}-usr-local-bundle
          paths:
            - /usr/local/bundle

      - run:
          name: Build Site
          command: ./script/build

      - run: Test that the site was built correctly
        command: |
          if test -e "./_site/index.html";then
            echo "It builds!"
            rm -Rf _site
          else
            echo "Huh. That's odd. The example site doesn't seem to build."
            exit 1
          fi
workflows:
  version: 2
  test_jekyll_build:
    jobs:
      - test
