version: 2
jobs:
  test:
    docker:
      - image: circleci/ruby:2.5
    steps:
      - checkout
      - restore_cache:
          keys:
            - jekyll-build-bundle-{{ checksum "Gemfile.lock" }}-vendor-bundle
      - run:
          name: Bundle Install
          command: bundle check --path ./vendor/bundle || bundle install --path ./vendor/bundle
      - save_cache:
          key: jekyll-build-bundle-{{ checksum "Gemfile.lock" }}-vendor-bundle
          paths:
            - vendor/bundle
      - run: bundle show colorator
      - run:
          name: Build Site
          command: ./script/build
      - run:
          name: Test that the site was built correctly
          command: |
            if test -e "./_site/index.html";then
              echo "It builds!"
            else
              echo "Huh. That's odd. The example site doesn't seem to build."
              exit 1
            fi
workflows:
  version: 2
  test_jekyll_build:
    jobs:
      - test
