version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.7-node
    steps:
      - checkout
      - restore_cache:
          keys:
            - jekyll-build-npm-{{ checksum "package-lock.json" }}
      - run:
          name: Update npm to v7
          command: npm i -g npm
      - run:
          name: Run npm install
          command: npm i
      - save_cache:
          key: jekyll-build-npm-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Run npm build Script
          command: npm test
      - restore_cache:
          keys:
            - jekyll-build-bundle-{{ checksum "Gemfile.lock" }}-vendor-bundle-ruby-2.5
      - run:
          name: Set bundler path
          command: bundle config set path "${PWD}/vendor/bundle"
      - run:
          name: Run bundle install
          command: bundle check || bundle install
      - save_cache:
          key: jekyll-build-bundle-{{ checksum "Gemfile.lock" }}-vendor-bundle-ruby-2.5
          paths:
            - vendor/bundle
      - run:
          name: Build Site
          command: ./script/build
      - run:
          name: Test site build
          command: |
            if test -e "./_site/index.html";then
              echo "It builds!"
            else
              echo "Huh. That's odd. The site doesn't seem to build."
              exit 1
            fi
