version: 2
jobs:
  test:
    docker:
      - image: circleci/ruby:2.5
    environment:
      TZ: "/usr/share/zoneinfo/America/Chicago"
    steps:
      - checkout
      - restore_cache:
          keys:
            - my-jekyll-build-bundle-{{ checksum "Gemfile.lock" }}
            - my-jekyll-build-bundle-
      - run:
          name: Bundle Install
          command: ./script/bootstrap
      - run: bundle show colorator
      - save_cache:
          key: my-jekyll-build-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Build and test
          command: ./script/cibuild
workflows:
  version: 2
  test_jekyll_build:
    jobs:
      - test
